package com.module.meituan;
public class Params{
	public static class PoiChannelParam {	
		/* request body参数*/
		public String latitude;
		public String longitude;
		public String page_index;
		public String page_size;
		public String sort_type;
		public String category_type;
		public String filter_type;
		public String second_category_type;
		public String navigate_type;
		public String activity_filter_codes;
		public String slider_select_data;
		public String load_type;
		public String preload;
		public String trace_tag;
		public String rank_trace_id;
		public String session_id;
		public String union_id;
		public String app;
		public String platform;
		public String push_token;
		public String wm_latitude;
		public String userid;
		public String wm_logintoken;
		public String wm_mac;
		public String wm_uuid;
		public String version;	
		public String wm_actual_longitude;
		public String wm_dtype;
	    public String request_id;
		public String wm_actual_latitude;
		public String wm_did;
		public String wm_ctype;
		public String wm_visitid;
		public String seq_id;
		public String partner;
		public String wm_appversion;
		public String wm_dversion;
		public String wm_longitude;
		public String wm_channel;
		public String wm_seq;
		public String req_time;
		public String region_id;
		//public String region_version;	
		
		/*query 参数*/
		public String ci;
		public String utm_content;
		public String utm_medium;
		public String uuid;
		public String utm_term;
		public String utm_campaign;
		public String utm_source;
	}
	
	static class PoiMenuParam{
		/* request body参数*/
		public String wmpoiid;
		public String product_spu_id;
		public String page_index;
		public String wm_latitude;
		public String wm_logintoken;
		public String wm_mac;
		public String request_id;
		public String poilist_mt_cityid;
		public String uuid;
		public String wm_actual_longitude;
		public String wm_actual_latitude;
		public String wm_ctype;
		public String app;
		public String wm_visitid;
		public String wm_did;
		public String userid;
		public String platform;
		public String seq_id;
		public String wm_dversion;
		public String wm_longitude;
		public String wm_channel;
		public String wm_uuid;
		public String version;
		public String wm_dtype;
		public String poilist_wm_cityid;
		public String push_token;
		public String partner;
		public String wm_seq;
		public String wm_appversion;
		
		/* query 参数*/
		public String ci;
		public String utm_content;
		public String utm_medium;
		public String utm_term;
		public String utm_campaign;
		public String utm_source;
	}
	
	static class PoiCommentParam{
		/* request body参数*/
		public String wmpoiid;
		public String page_offset;
		public String page_size;
		public String comment_score_type;
		public String label_id;
		public String wm_latitude;
		public String wm_logintoken;
		public String wm_mac;
		public String request_id;
		public String poilist_mt_cityid;
		public String uuid;
		public String wm_actual_longitude;
		public String wm_actual_latitude;
		public String wm_ctype;
		public String app;
		public String wm_visitid;
		public String wm_did;
		public String userid;
		public String platform;
		public String seq_id;
		public String wm_dversion;
		public String wm_longitude;
		public String wm_channel;
		public String wm_uuid;
		public String version;
		public String wm_dtype;
		public String poilist_wm_cityid;
		public String push_token;
		public String partner;
		public String wm_seq;
		public String wm_appversion;
		
		/* query 参数*/
		public String ci;
		public String utm_content;
		public String utm_medium;
		public String utm_term;
		public String utm_campaign;
		public String utm_source;
		
	}
	
	static class PoiDetailParam{
		/* request body参数*/
		public String wmpoiid;
		public String wm_latitude;
		public String wm_logintoken;
		public String wm_mac;
		public String request_id;
		public String poilist_mt_cityid;
		public String uuid;
		public String wm_actual_longitude;
		public String wm_actual_latitude;
		public String wm_ctype;
		public String app;
		public String wm_visitid;
		public String wm_did;
		public String userid;
		public String platform;
		public String seq_id;
		public String wm_dversion;
		public String wm_longitude;
		public String wm_channel;
		public String wm_uuid;
		public String version;
		public String wm_dtype;
		public String poilist_wm_cityid;
		public String push_token;
		public String partner;
		public String wm_seq;
		public String wm_appversion;
		
		/* query 参数*/
		public String ci;
		public String utm_content;
		public String utm_medium;
		public String utm_term;
		public String utm_campaign;
		public String utm_source;
	}
}
